[package]
name = "hindex_reader"
version = "0.1.0"
authors = ["JGeiser9 <32041734+JGeiser9@users.noreply.github.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.1", features = ["postgres"] }
dotenv = "0.13.0"
